# Generated by Django 5.1.4 on 2026-03-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tier', models.CharField(choices=[('high', 'High Complexity'), ('medium', 'Medium Complexity'), ('low', 'Low Complexity')], max_length=10)),
                ('base_score', models.IntegerField()),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dosage', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('is_specialty', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=100)),
                ('specialty_tier', models.CharField(choices=[('high', 'High Complexity Specialty'), ('medium', 'Medium Complexity Specialty'), ('low', 'Other Specialist'), ('base', 'Primary Care')], default='low', max_length=10)),
                ('specialty_score', models.IntegerField(default=2)),
                ('npi', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['specialty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DemographicFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_band', models.CharField(choices=[('under_65', 'Under 65'), ('65_70', '65-70'), ('70_75', '70-75'), ('75_80', '75-80'), ('80_plus', '80+'), ('unknown', 'Unknown')], max_length=20)),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unknown', 'Unknown')], max_length=10)),
                ('base_score', models.IntegerField()),
            ],
            options={
                'ordering': ['age_band', 'sex'],
                'unique_together': {('age_band', 'sex')},
            },
        ),
    ]
